# Generated by Django 3.2.7 on 2021-10-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='User_id',
        ),
    ]
